name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    name: poe check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: astral-sh/setup-uv@v3
      - name: Install dependencies
        run: |
          uv venv
          uv pip install -e ".[dev]"
      - name: Run poe check
        run: |
          source .venv/bin/activate
          poe check

  test:
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    needs: check
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v3
      - name: Install dependencies
        run: |
          uv venv
          uv pip install -e ".[dev]"
      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest tests/